#+LaTeX: \toggleurlstyle
* Experience
** Junior Software Developer at [[https://machobear.ca/][Machobear Studios Inc.]]
#+LaTeX: \vspace{-1.35ex}
*** \orange{Remote} --- May 2020 - August 2020
#+LaTeX: \vspace{1.35ex}
#+LaTeX: \vspace{-0.55ex}
*Vancouver, BC*
- Develop accessible and responsive front-end features for **[[https://liv.rent/][liv.rent]]** rental platform.
- Construct a performant and bug-free experience for end users using React, GrahpQL and Redux.
- Communicate with product management team as-needed to ensure features are implemented as desired.
#+LaTeX: \vspace{0.5ex}
** Software Developer at [[https://ftsinc.com][FTS Inc.]]
#+LaTeX: \vspace{-1.5ex}
*** \orange{Contractor} --- January 2019 - August 2019
#+LaTeX: \vspace{2.4ex}
*** \orange{Co-op} --- May 2018 - December 2018
#+LaTeX: \vspace{-2.7ex}
*Victoria, BC*
- Develop new features and services for web applications and APIs communicating with remote weather stations.
- Configure, manage and version software projects using automated deployment tools.
- Integrate Open Source tools used to configure IoT devices with existing software.
